version: '2'
services:

  cti-stix-gateway:
    container_name: cti-stix-gateway
    image: nginx
    volumes:
     - ./cti-stix-gateway/nginx/conf.d:/etc/nginx/conf.d
    ports:
     - "8080:80"
    links:
     - cti-stix-discover
     - cti-stix-store
     - cti-stix-ui
  cti-stix-discover:
    container_name: cti-stix-discover
    build: cti-stix-discover
    links:
     - cti-stix-store:cti-stix-store
  cti-stix-store:
    container_name: cti-stix-store
    build: cti-stix-store


  cti-stix-ui: 
    container_name: cti-stix-ui
    build: cti-stix-ui
    links:
    - cti-stix-store
    ports:
    - "50000:50000"
