version: '2'
services:
  cti-stix-store:
    container_name: cti-stix-store
    build: .
    volumes:
     - .:/usr/share/cti-stix-store
    ports:
     - "3000:3000"
    links:
     - mongo:repository
  mongo:
    image: mongo
    container_name: mongo
    ports:
     - "27017:27017"
